server:
  port: 28081

spring:
  application:
    name: zyn-sys
  profiles:
    active: @spring.profiles.active@
  config:
    import:
      - classpath:zyn-conf-common.yml
      - classpath:zyn-conf-@spring.profiles.active@.yml
  jackson:
    time-zone: Asia/Shanghai
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false

zyn:
  satoken:
    root-user-id: 0
